// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Test
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FOO int32

const (
	FOO_X FOO = 0
)

var FOO_name = map[int32]string{
	0: "X",
}
var FOO_value = map[string]int32{
	"X": 0,
}

func (x FOO) String() string {
	return proto.EnumName(FOO_name, int32(x))
}
func (FOO) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Test struct {
	Label         string      `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Type          int32       `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Reps          []int64     `protobuf:"varint,3,rep,packed,name=reps" json:"reps,omitempty"`
	OptionalGroup *Test_Group `protobuf:"bytes,4,opt,name=OptionalGroup" json:"OptionalGroup,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetOptionalGroup() *Test_Group {
	if m != nil {
		return m.OptionalGroup
	}
	return nil
}

type Test_Group struct {
	RequiedField string `protobuf:"bytes,1,opt,name=RequiedField" json:"RequiedField,omitempty"`
}

func (m *Test_Group) Reset()                    { *m = Test_Group{} }
func (m *Test_Group) String() string            { return proto.CompactTextString(m) }
func (*Test_Group) ProtoMessage()               {}
func (*Test_Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Test_Group) GetRequiedField() string {
	if m != nil {
		return m.RequiedField
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "example.Test")
	proto.RegisterType((*Test_Group)(nil), "example.Test.Group")
	proto.RegisterEnum("example.FOO", FOO_name, FOO_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55,
	0x5a, 0xc3, 0xc8, 0xc5, 0x12, 0x92, 0x5a, 0x5c, 0x22, 0x24, 0xc2, 0xc5, 0x9a, 0x93, 0x98, 0x94,
	0x9a, 0x23, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x54,
	0x16, 0xa4, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0xa2, 0xd4, 0x82,
	0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0xe6, 0x20, 0x30, 0x5b, 0xc8, 0x92, 0x8b, 0xd7, 0xbf, 0xa0,
	0x24, 0x33, 0x3f, 0x2f, 0x31, 0xc7, 0xbd, 0x28, 0xbf, 0xb4, 0x40, 0x82, 0x45, 0x81, 0x51, 0x83,
	0xdb, 0x48, 0x58, 0x0f, 0x6a, 0x8f, 0x1e, 0xc8, 0x0e, 0x3d, 0xb0, 0x54, 0x10, 0xaa, 0x4a, 0x29,
	0x6d, 0x2e, 0x56, 0x30, 0x43, 0x48, 0x89, 0x8b, 0x27, 0x28, 0xb5, 0xb0, 0x34, 0x33, 0x35, 0xc5,
	0x2d, 0x33, 0x35, 0x27, 0x05, 0xea, 0x10, 0x14, 0x31, 0x2d, 0x1e, 0x2e, 0x66, 0x37, 0x7f, 0x7f,
	0x21, 0x56, 0x2e, 0xc6, 0x08, 0x01, 0x86, 0x24, 0x36, 0xb0, 0x67, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x92, 0xfe, 0x74, 0x9a, 0xda, 0x00, 0x00, 0x00,
}
