// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package loginreq is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	Loginreq
	Packet
	PktHead
	PktOpt
*/
package loginreq

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Loginreq_LOGIN_TYPE int32

const (
	Loginreq_LOGIN_TYPE_GUEST Loginreq_LOGIN_TYPE = 0
)

var Loginreq_LOGIN_TYPE_name = map[int32]string{
	0: "LOGIN_TYPE_GUEST",
}
var Loginreq_LOGIN_TYPE_value = map[string]int32{
	"LOGIN_TYPE_GUEST": 0,
}

func (x Loginreq_LOGIN_TYPE) String() string {
	return proto.EnumName(Loginreq_LOGIN_TYPE_name, int32(x))
}
func (Loginreq_LOGIN_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Loginreq_GENDER_TYPE int32

const (
	Loginreq_GENDER_TYPE_MALE Loginreq_GENDER_TYPE = 0
)

var Loginreq_GENDER_TYPE_name = map[int32]string{
	0: "GENDER_TYPE_MALE",
}
var Loginreq_GENDER_TYPE_value = map[string]int32{
	"GENDER_TYPE_MALE": 0,
}

func (x Loginreq_GENDER_TYPE) String() string {
	return proto.EnumName(Loginreq_GENDER_TYPE_name, int32(x))
}
func (Loginreq_GENDER_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Loginreq struct {
	Type        Loginreq_LOGIN_TYPE  `protobuf:"varint,1,opt,name=Type,enum=loginreq.Loginreq_LOGIN_TYPE" json:"Type,omitempty"`
	AccessToken string               `protobuf:"bytes,2,opt,name=AccessToken" json:"AccessToken,omitempty"`
	Gender      Loginreq_GENDER_TYPE `protobuf:"varint,3,opt,name=Gender,enum=loginreq.Loginreq_GENDER_TYPE" json:"Gender,omitempty"`
}

func (m *Loginreq) Reset()                    { *m = Loginreq{} }
func (m *Loginreq) String() string            { return proto.CompactTextString(m) }
func (*Loginreq) ProtoMessage()               {}
func (*Loginreq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Loginreq) GetType() Loginreq_LOGIN_TYPE {
	if m != nil {
		return m.Type
	}
	return Loginreq_LOGIN_TYPE_GUEST
}

func (m *Loginreq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Loginreq) GetGender() Loginreq_GENDER_TYPE {
	if m != nil {
		return m.Gender
	}
	return Loginreq_GENDER_TYPE_MALE
}

type Packet struct {
	Head *PktHead `protobuf:"bytes,1,opt,name=Head" json:"Head,omitempty"`
	Body []byte   `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *Packet) Reset()                    { *m = Packet{} }
func (m *Packet) String() string            { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()               {}
func (*Packet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Packet) GetHead() *PktHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Packet) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type PktHead struct {
	Opt      *PktOpt            `protobuf:"bytes,1,opt,name=Opt" json:"Opt,omitempty"`
	PktInfos []*PktHead_PktInfo `protobuf:"bytes,2,rep,name=PktInfos" json:"PktInfos,omitempty"`
}

func (m *PktHead) Reset()                    { *m = PktHead{} }
func (m *PktHead) String() string            { return proto.CompactTextString(m) }
func (*PktHead) ProtoMessage()               {}
func (*PktHead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PktHead) GetOpt() *PktOpt {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *PktHead) GetPktInfos() []*PktHead_PktInfo {
	if m != nil {
		return m.PktInfos
	}
	return nil
}

type PktHead_PktInfo struct {
	Cmd uint32 `protobuf:"varint,1,opt,name=Cmd" json:"Cmd,omitempty"`
	Len uint32 `protobuf:"varint,2,opt,name=Len" json:"Len,omitempty"`
}

func (m *PktHead_PktInfo) Reset()                    { *m = PktHead_PktInfo{} }
func (m *PktHead_PktInfo) String() string            { return proto.CompactTextString(m) }
func (*PktHead_PktInfo) ProtoMessage()               {}
func (*PktHead_PktInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *PktHead_PktInfo) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *PktHead_PktInfo) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type PktOpt struct {
	Version uint32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	Mtkey   uint64 `protobuf:"varint,2,opt,name=Mtkey" json:"Mtkey,omitempty"`
	Skey    uint64 `protobuf:"varint,3,opt,name=Skey" json:"Skey,omitempty"`
	Seq     uint32 `protobuf:"varint,4,opt,name=Seq" json:"Seq,omitempty"`
	Time    uint64 `protobuf:"varint,5,opt,name=Time" json:"Time,omitempty"`
	UID     string `protobuf:"bytes,6,opt,name=UID" json:"UID,omitempty"`
	Device  string `protobuf:"bytes,7,opt,name=Device" json:"Device,omitempty"`
	Channel string `protobuf:"bytes,8,opt,name=Channel" json:"Channel,omitempty"`
	Lang    string `protobuf:"bytes,9,opt,name=Lang" json:"Lang,omitempty"`
}

func (m *PktOpt) Reset()                    { *m = PktOpt{} }
func (m *PktOpt) String() string            { return proto.CompactTextString(m) }
func (*PktOpt) ProtoMessage()               {}
func (*PktOpt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PktOpt) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *PktOpt) GetMtkey() uint64 {
	if m != nil {
		return m.Mtkey
	}
	return 0
}

func (m *PktOpt) GetSkey() uint64 {
	if m != nil {
		return m.Skey
	}
	return 0
}

func (m *PktOpt) GetSeq() uint32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PktOpt) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PktOpt) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

func (m *PktOpt) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *PktOpt) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PktOpt) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func init() {
	proto.RegisterType((*Loginreq)(nil), "loginreq.loginreq")
	proto.RegisterType((*Packet)(nil), "loginreq.Packet")
	proto.RegisterType((*PktHead)(nil), "loginreq.PktHead")
	proto.RegisterType((*PktHead_PktInfo)(nil), "loginreq.PktHead.PktInfo")
	proto.RegisterType((*PktOpt)(nil), "loginreq.PktOpt")
	proto.RegisterEnum("loginreq.Loginreq_LOGIN_TYPE", Loginreq_LOGIN_TYPE_name, Loginreq_LOGIN_TYPE_value)
	proto.RegisterEnum("loginreq.Loginreq_GENDER_TYPE", Loginreq_GENDER_TYPE_name, Loginreq_GENDER_TYPE_value)
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0xdd, 0x6c, 0xb2, 0x69, 0xf7, 0xc6, 0x95, 0x38, 0x2c, 0x32, 0x0a, 0x4a, 0x19, 0x11, 0xfa,
	0x62, 0xc1, 0x8a, 0xbe, 0xaf, 0x6d, 0xa8, 0x85, 0xee, 0x36, 0x4c, 0xb2, 0x82, 0x4f, 0x25, 0xa6,
	0xd7, 0x35, 0x64, 0x77, 0x92, 0x26, 0x41, 0xd8, 0xef, 0xf0, 0xaf, 0xfc, 0x0a, 0x3f, 0x45, 0xee,
	0x4d, 0xba, 0xa9, 0xe8, 0xdb, 0x39, 0xe7, 0x9e, 0x39, 0x67, 0x6e, 0x32, 0xe0, 0xdd, 0x16, 0x37,
	0x99, 0x99, 0x94, 0x55, 0xd1, 0x14, 0x62, 0xc8, 0xa4, 0xc2, 0x9d, 0xfa, 0x6d, 0xc1, 0x03, 0x11,
	0x6f, 0xc1, 0x89, 0xef, 0x4b, 0x94, 0xd6, 0xc8, 0x1a, 0x3f, 0x9e, 0xbe, 0x98, 0xec, 0x07, 0x3d,
	0x58, 0xad, 0x17, 0xcb, 0xab, 0x4d, 0xfc, 0x25, 0x0c, 0x34, 0x5b, 0xc5, 0x08, 0xbc, 0x8b, 0x34,
	0xc5, 0xba, 0x8e, 0x8b, 0x1c, 0x8d, 0x3c, 0x1e, 0x59, 0xe3, 0x53, 0x7d, 0x28, 0x89, 0x0f, 0xe0,
	0x2e, 0xd0, 0x6c, 0xb1, 0x92, 0x36, 0xc7, 0xbe, 0xfc, 0x4f, 0xec, 0x22, 0xb8, 0x9a, 0x07, 0xba,
	0xcd, 0xed, 0xdc, 0x4a, 0x01, 0xf4, 0x6d, 0xe2, 0x1c, 0xfc, 0x9e, 0x6d, 0x16, 0xd7, 0x41, 0x14,
	0xfb, 0x47, 0xea, 0x15, 0x78, 0x07, 0x47, 0xc9, 0x74, 0x40, 0x37, 0x97, 0x17, 0xab, 0xc0, 0x3f,
	0x52, 0x33, 0x70, 0xc3, 0x24, 0xcd, 0xb1, 0x11, 0xaf, 0xc1, 0xf9, 0x84, 0xc9, 0x96, 0xf7, 0xf3,
	0xa6, 0x4f, 0xfa, 0xfe, 0x30, 0x6f, 0x68, 0xa0, 0x79, 0x2c, 0x04, 0x38, 0x1f, 0x8b, 0xed, 0x3d,
	0x2f, 0xf3, 0x48, 0x33, 0x56, 0x3f, 0x2d, 0x18, 0x74, 0x2e, 0xa1, 0xc0, 0x5e, 0x97, 0x4d, 0x97,
	0xe2, 0xff, 0x95, 0xb2, 0x2e, 0x1b, 0x4d, 0x43, 0xf1, 0x1e, 0x86, 0x61, 0xde, 0x2c, 0xcd, 0xb7,
	0xa2, 0x96, 0xc7, 0x23, 0x7b, 0xec, 0x4d, 0x9f, 0xfd, 0x53, 0x37, 0xe9, 0x1c, 0xfa, 0xc1, 0xfa,
	0xfc, 0x0d, 0xb7, 0x10, 0x16, 0x3e, 0xd8, 0xb3, 0xbb, 0xf6, 0xae, 0x67, 0x9a, 0x20, 0x29, 0xab,
	0xee, 0x1b, 0x9f, 0x69, 0x82, 0xea, 0x97, 0x05, 0x6e, 0xdb, 0x2a, 0x24, 0x0c, 0x3e, 0x63, 0x55,
	0x67, 0x85, 0xe9, 0x8e, 0xec, 0xa9, 0x38, 0x87, 0x93, 0xcb, 0x26, 0xc7, 0x76, 0x1f, 0x47, 0xb7,
	0x84, 0x96, 0x8c, 0x48, 0xb4, 0x59, 0x64, 0x4c, 0x05, 0x11, 0xee, 0xa4, 0xd3, 0x16, 0x44, 0xb8,
	0x23, 0x57, 0x9c, 0xdd, 0xa1, 0x3c, 0x69, 0x5d, 0x84, 0xc9, 0x75, 0xbd, 0x9c, 0x4b, 0x97, 0x7f,
	0x35, 0x41, 0xf1, 0x14, 0xdc, 0x39, 0xfe, 0xc8, 0x52, 0x94, 0x03, 0x16, 0x3b, 0x46, 0x77, 0x9a,
	0x7d, 0x4f, 0x8c, 0xc1, 0x5b, 0x39, 0xe4, 0xc1, 0x9e, 0x52, 0xee, 0x2a, 0x31, 0x37, 0xf2, 0x94,
	0x65, 0xc6, 0x5f, 0x5d, 0x7e, 0x9b, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x24, 0xac, 0xf8,
	0x0e, 0xaa, 0x02, 0x00, 0x00,
}
