// Code generated by protoc-gen-go. DO NOT EDIT.
// source: college.proto

/*
Package pbtest is a generated protocol buffer package.

It is generated from these files:
	college.proto
	men.proto
	student.proto

It has these top-level messages:
	CollegeStudent
	Men
	Student
*/
package pbtest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CollegeStudent struct {
	Student       *Student `protobuf:"bytes,1,opt,name=student" json:"student,omitempty"`
	Major_Project string   `protobuf:"bytes,2,opt,name=Major_Project,json=MajorProject" json:"Major_Project,omitempty"`
	Grades        float64  `protobuf:"fixed64,3,opt,name=Grades" json:"Grades,omitempty"`
}

func (m *CollegeStudent) Reset()                    { *m = CollegeStudent{} }
func (m *CollegeStudent) String() string            { return proto.CompactTextString(m) }
func (*CollegeStudent) ProtoMessage()               {}
func (*CollegeStudent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CollegeStudent) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func (m *CollegeStudent) GetMajor_Project() string {
	if m != nil {
		return m.Major_Project
	}
	return ""
}

func (m *CollegeStudent) GetGrades() float64 {
	if m != nil {
		return m.Grades
	}
	return 0
}

func init() {
	proto.RegisterType((*CollegeStudent)(nil), "pbtest.CollegeStudent")
}

func init() { proto.RegisterFile("college.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x2a, 0x49, 0x2d,
	0x2e, 0x91, 0xe2, 0x2d, 0x2e, 0x29, 0x4d, 0x49, 0xcd, 0x2b, 0x81, 0x08, 0x2b, 0x55, 0x70, 0xf1,
	0x39, 0x43, 0xd4, 0x05, 0x43, 0xc4, 0x85, 0x34, 0xb9, 0xd8, 0xa1, 0x4a, 0x24, 0x18, 0x15, 0x18,
	0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x20, 0x5a, 0xf5, 0xa0, 0x2a, 0x82, 0x60, 0xf2, 0x42, 0xca, 0x5c,
	0xbc, 0xbe, 0x89, 0x59, 0xf9, 0x45, 0xf1, 0x01, 0x45, 0xf9, 0x59, 0xa9, 0xc9, 0x25, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x3c, 0x60, 0x41, 0xa8, 0x98, 0x90, 0x18, 0x17, 0x9b, 0x7b, 0x51,
	0x62, 0x4a, 0x6a, 0xb1, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x94, 0x97, 0xc4, 0x06, 0x76,
	0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xef, 0x66, 0x8e, 0xa8, 0x00, 0x00, 0x00,
}
