// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

/*
Package aladinfun_TripleDream_proto is a generated protocol buffer package.

It is generated from these files:
	base.proto
	cmd.proto
	db.proto
	enum.proto
	game.proto
	inner_game.proto
	struct.proto
	user.proto

It has these top-level messages:
	RspHead
	UserSumm
	UserCore
	UserStatis
	UserBag
	UserGameRound
	UserMsg
	AppUpdateInfo
	LoginInfo
	HelloReq
	HelloRsp
	UserData
	LoginReq
	LoginRsp
	RankReq
	RankRsp
	FriendListReq
	FriendListRsp
	OprHistory
	SettleRoundReq
	SettleRoundRsp
	BuildReq
	BuildRsp
	SetBDStatusReq
	SetBDStatusRsp
	FriIslandReq
	FriIslandRsp
	IslandFriSumm
	IslandMapReq
	IslandMapRsp
	MsgReq
	MsgRsp
	BuyReq
	BuyRsp
	AccLoginReq
	AccLoginRsp
	CoreGetUserCoreReq
	CoreGetUserCoreRsp
	CoreChgUserCoreReq
	CoreChgUserCoreRsp
	CoreBuildReq
	CoreBuildRsp
	Component
	Prize
	UserSocial
	UserProp
	Bag
	StatisComp
	GameRound
	MsgTmpl
	UserIsland
*/
package aladinfun_TripleDream_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RspHead struct {
	RetCode uint32 `protobuf:"varint,1,opt,name=RetCode" json:"RetCode,omitempty"`
}

func (m *RspHead) Reset()                    { *m = RspHead{} }
func (m *RspHead) String() string            { return proto.CompactTextString(m) }
func (*RspHead) ProtoMessage()               {}
func (*RspHead) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RspHead) GetRetCode() uint32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*RspHead)(nil), "aladinfun.TripleDream.proto.RspHead")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4a, 0x2c, 0x4e,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x4e, 0xcc, 0x49, 0x4c, 0xc9, 0xcc, 0x4b, 0x2b,
	0xcd, 0xd3, 0x0b, 0x29, 0xca, 0x2c, 0xc8, 0x49, 0x75, 0x29, 0x4a, 0x4d, 0xcc, 0x85, 0x48, 0x2a,
	0x29, 0x73, 0xb1, 0x07, 0x15, 0x17, 0x78, 0xa4, 0x26, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x07, 0xa5,
	0x96, 0x38, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xc1, 0xb8, 0x49, 0x6c,
	0x60, 0xb5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x59, 0x8a, 0x3c, 0xcc, 0x56, 0x00, 0x00,
	0x00,
}
