// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enum.proto

package aladinfun_TripleDream_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LOGIN_TYPE int32

const (
	LOGIN_TYPE_LOGIN_TYPE_INIT     LOGIN_TYPE = 0
	LOGIN_TYPE_LOGIN_TYPE_GUEST    LOGIN_TYPE = 10
	LOGIN_TYPE_LOGIN_TYPE_FACEBOOK LOGIN_TYPE = 20
)

var LOGIN_TYPE_name = map[int32]string{
	0:  "LOGIN_TYPE_INIT",
	10: "LOGIN_TYPE_GUEST",
	20: "LOGIN_TYPE_FACEBOOK",
}
var LOGIN_TYPE_value = map[string]int32{
	"LOGIN_TYPE_INIT":     0,
	"LOGIN_TYPE_GUEST":    10,
	"LOGIN_TYPE_FACEBOOK": 20,
}

func (x LOGIN_TYPE) String() string {
	return proto.EnumName(LOGIN_TYPE_name, int32(x))
}
func (LOGIN_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type BAG_TYPE int32

const (
	BAG_TYPE_BAG_TYPE_INIT     BAG_TYPE = 0
	BAG_TYPE_BAG_TYPE_USER     BAG_TYPE = 1
	BAG_TYPE_BAG_TYPE_ACTIVITY BAG_TYPE = 2
)

var BAG_TYPE_name = map[int32]string{
	0: "BAG_TYPE_INIT",
	1: "BAG_TYPE_USER",
	2: "BAG_TYPE_ACTIVITY",
}
var BAG_TYPE_value = map[string]int32{
	"BAG_TYPE_INIT":     0,
	"BAG_TYPE_USER":     1,
	"BAG_TYPE_ACTIVITY": 2,
}

func (x BAG_TYPE) String() string {
	return proto.EnumName(BAG_TYPE_name, int32(x))
}
func (BAG_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

type GENDER_TYPE int32

const (
	GENDER_TYPE_GENDER_TYPE_INIT   GENDER_TYPE = 0
	GENDER_TYPE_GENDER_TYPE_MALE   GENDER_TYPE = 1
	GENDER_TYPE_GENDER_TYPE_FEMALE GENDER_TYPE = 2
)

var GENDER_TYPE_name = map[int32]string{
	0: "GENDER_TYPE_INIT",
	1: "GENDER_TYPE_MALE",
	2: "GENDER_TYPE_FEMALE",
}
var GENDER_TYPE_value = map[string]int32{
	"GENDER_TYPE_INIT":   0,
	"GENDER_TYPE_MALE":   1,
	"GENDER_TYPE_FEMALE": 2,
}

func (x GENDER_TYPE) String() string {
	return proto.EnumName(GENDER_TYPE_name, int32(x))
}
func (GENDER_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type PRIZE_TYPE int32

const (
	PRIZE_TYPE_PRIZE_TYPE_INIT    PRIZE_TYPE = 0
	PRIZE_TYPE_PRIZE_TYPE_DIAMOND PRIZE_TYPE = 1
	PRIZE_TYPE_PRIZE_TYPE_GOLD    PRIZE_TYPE = 2
	PRIZE_TYPE_PRIZE_TYPE_PROP    PRIZE_TYPE = 3
)

var PRIZE_TYPE_name = map[int32]string{
	0: "PRIZE_TYPE_INIT",
	1: "PRIZE_TYPE_DIAMOND",
	2: "PRIZE_TYPE_GOLD",
	3: "PRIZE_TYPE_PROP",
}
var PRIZE_TYPE_value = map[string]int32{
	"PRIZE_TYPE_INIT":    0,
	"PRIZE_TYPE_DIAMOND": 1,
	"PRIZE_TYPE_GOLD":    2,
	"PRIZE_TYPE_PROP":    3,
}

func (x PRIZE_TYPE) String() string {
	return proto.EnumName(PRIZE_TYPE_name, int32(x))
}
func (PRIZE_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

type DEDUCT_TYPE int32

const (
	DEDUCT_TYPE_DEDUCT_TYPE_INIT    DEDUCT_TYPE = 0
	DEDUCT_TYPE_DEDUCT_TYPE_DIAMOND DEDUCT_TYPE = 1
	DEDUCT_TYPE_DEDUCT_TYPE_GOLD    DEDUCT_TYPE = 2
	DEDUCT_TYPE_DEDUCT_TYPE_PROP    DEDUCT_TYPE = 3
)

var DEDUCT_TYPE_name = map[int32]string{
	0: "DEDUCT_TYPE_INIT",
	1: "DEDUCT_TYPE_DIAMOND",
	2: "DEDUCT_TYPE_GOLD",
	3: "DEDUCT_TYPE_PROP",
}
var DEDUCT_TYPE_value = map[string]int32{
	"DEDUCT_TYPE_INIT":    0,
	"DEDUCT_TYPE_DIAMOND": 1,
	"DEDUCT_TYPE_GOLD":    2,
	"DEDUCT_TYPE_PROP":    3,
}

func (x DEDUCT_TYPE) String() string {
	return proto.EnumName(DEDUCT_TYPE_name, int32(x))
}
func (DEDUCT_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

// building status, building may have several status in the same time
type BD_STATUS int32

const (
	BD_STATUS_BD_STATUS_INIT   BD_STATUS = 0
	BD_STATUS_BD_STATUS_LOOTED BD_STATUS = 1
	BD_STATUS_BD_STATUS_SHIELD BD_STATUS = 2
	BD_STATUS_BD_STATUS_TRAP   BD_STATUS = 3
)

var BD_STATUS_name = map[int32]string{
	0: "BD_STATUS_INIT",
	1: "BD_STATUS_LOOTED",
	2: "BD_STATUS_SHIELD",
	3: "BD_STATUS_TRAP",
}
var BD_STATUS_value = map[string]int32{
	"BD_STATUS_INIT":   0,
	"BD_STATUS_LOOTED": 1,
	"BD_STATUS_SHIELD": 2,
	"BD_STATUS_TRAP":   3,
}

func (x BD_STATUS) String() string {
	return proto.EnumName(BD_STATUS_name, int32(x))
}
func (BD_STATUS) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func init() {
	proto.RegisterEnum("aladinfun.TripleDream.proto.LOGIN_TYPE", LOGIN_TYPE_name, LOGIN_TYPE_value)
	proto.RegisterEnum("aladinfun.TripleDream.proto.BAG_TYPE", BAG_TYPE_name, BAG_TYPE_value)
	proto.RegisterEnum("aladinfun.TripleDream.proto.GENDER_TYPE", GENDER_TYPE_name, GENDER_TYPE_value)
	proto.RegisterEnum("aladinfun.TripleDream.proto.PRIZE_TYPE", PRIZE_TYPE_name, PRIZE_TYPE_value)
	proto.RegisterEnum("aladinfun.TripleDream.proto.DEDUCT_TYPE", DEDUCT_TYPE_name, DEDUCT_TYPE_value)
	proto.RegisterEnum("aladinfun.TripleDream.proto.BD_STATUS", BD_STATUS_name, BD_STATUS_value)
}

func init() { proto.RegisterFile("enum.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xdf, 0x4e, 0xc2, 0x30,
	0x14, 0xc6, 0x05, 0x12, 0xa3, 0x87, 0xa8, 0x87, 0x82, 0x70, 0xe1, 0x1b, 0xec, 0x82, 0x1b, 0x9f,
	0xa0, 0xac, 0x87, 0xda, 0x38, 0xd6, 0xba, 0x75, 0x26, 0x78, 0xb3, 0x4c, 0x9d, 0x91, 0x04, 0x07,
	0x59, 0xe4, 0xfd, 0x4d, 0xc6, 0xfe, 0xd4, 0xdd, 0xed, 0xfb, 0xed, 0xec, 0xfb, 0x9d, 0x35, 0x05,
	0xc8, 0x8b, 0xd3, 0xcf, 0xf2, 0x58, 0x1e, 0x7e, 0x0f, 0xec, 0x21, 0xdb, 0x67, 0x9f, 0xbb, 0xe2,
	0xeb, 0x54, 0x2c, 0x6d, 0xb9, 0x3b, 0xee, 0x73, 0x51, 0xe6, 0x59, 0xfd, 0xd2, 0x33, 0x00, 0x81,
	0x96, 0x2a, 0x4c, 0xed, 0xd6, 0x10, 0x9b, 0xc2, 0x5d, 0x97, 0x52, 0x15, 0x2a, 0x8b, 0x17, 0x6c,
	0x06, 0xe8, 0x40, 0x99, 0x50, 0x6c, 0x11, 0xd8, 0x02, 0xa6, 0x0e, 0x5d, 0x73, 0x9f, 0x56, 0x5a,
	0x3f, 0xe3, 0xcc, 0x93, 0x70, 0xb5, 0xe2, 0xf2, 0xdc, 0x37, 0x81, 0x9b, 0xe6, 0xb9, 0x69, 0x73,
	0x51, 0x12, 0x53, 0x84, 0x03, 0x76, 0x0f, 0x93, 0x16, 0x71, 0xdf, 0xaa, 0x57, 0x65, 0xb7, 0x38,
	0xf4, 0x5e, 0x60, 0x2c, 0x29, 0x14, 0x14, 0x9d, 0xbb, 0x66, 0x80, 0x4e, 0x74, 0x96, 0x73, 0xe9,
	0x86, 0x07, 0x84, 0x03, 0x36, 0x07, 0xe6, 0xd2, 0x35, 0x55, 0x7c, 0xe8, 0x7d, 0x00, 0x98, 0x48,
	0xbd, 0x51, 0xfb, 0xb7, 0x5d, 0x6a, 0x0a, 0xe7, 0xc0, 0x1c, 0x28, 0x14, 0xdf, 0xe8, 0x50, 0xe0,
	0xa0, 0x37, 0x2c, 0x75, 0x20, 0x70, 0xd8, 0x83, 0x26, 0xd2, 0x06, 0x47, 0xde, 0x37, 0x8c, 0x05,
	0x89, 0xc4, 0xb7, 0xed, 0xde, 0x4e, 0x6c, 0x34, 0x0b, 0x98, 0xba, 0xb4, 0xf3, 0xf4, 0xc6, 0x6b,
	0x51, 0x8f, 0xd6, 0xa6, 0x14, 0xae, 0x57, 0x22, 0x8d, 0x2d, 0xb7, 0x49, 0xcc, 0x18, 0xdc, 0xb6,
	0xc1, 0x39, 0x9d, 0x8e, 0x05, 0x5a, 0x5b, 0xaa, 0x15, 0x1d, 0x8d, 0x9f, 0x14, 0x55, 0x8a, 0x7f,
	0xdf, 0xdb, 0x88, 0x1b, 0x1c, 0xbd, 0x5f, 0x56, 0x97, 0xe4, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x5a, 0xbf, 0x2a, 0x4f, 0x02, 0x00, 0x00,
}
